# Generated by Django 2.2.1 on 2019-05-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_merge_20190514_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('portion', models.IntegerField()),
                ('price', models.IntegerField(default=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingr',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={},
        ),
        migrations.RemoveField(
            model_name='check',
            name='fo',
        ),
        migrations.RemoveField(
            model_name='check',
            name='foods',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(default='UNDONE', max_length=100),
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='magazine',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='api.Catalog'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='check',
            name='ma',
            field=models.ManyToManyField(to='api.Magazine'),
        ),
        migrations.AddField(
            model_name='check',
            name='magazines',
            field=models.ManyToManyField(related_name='food', to='api.Magazine'),
        ),
    ]
