# Generated by Django 2.2.1 on 2019-05-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190528_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='portion',
        ),
    ]
