# Generated by Django 2.2.2 on 2019-06-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_magazine_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.CharField(default='1', max_length=500),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Magazine')),
            ],
        ),
    ]
