# Generated by Django 2.2.1 on 2019-06-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190607_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('sender', models.CharField(default='codefazzer@gmail.com', max_length=250)),
                ('password', models.CharField(default='123456789Bd', max_length=200)),
                ('dest', models.CharField(max_length=100)),
            ],
        ),
    ]
