# Generated by Django 2.2.1 on 2019-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190608_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
