# Generated by Django 2.2.1 on 2019-06-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_magazine_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='image',
        ),
    ]
