# Generated by Django 2.2.1 on 2019-06-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_magazine_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='img',
            new_name='image',
        ),
    ]
