# Generated by Django 2.2.1 on 2019-06-09 07:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190609_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='date',
            field=models.DateTimeField(default=api.models.todayttime),
        ),
    ]
