# Generated by Django 2.2.2 on 2019-06-09 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_auto_20190609_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.ManyToManyField(to='api.Magazine')),
                ('magazines', models.ManyToManyField(related_name='foodI', to='api.Magazine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderI', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
