# Generated by Django 2.2.2 on 2019-06-09 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='ma',
            field=models.ManyToManyField(default=None, null=True, to='api.Magazine'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
