# Generated by Django 2.2.2 on 2019-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190609_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='ma',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='api.Magazine'),
        ),
    ]
