# Generated by Django 2.2.2 on 2019-06-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_magazine_date'),
        ('api', '0037_auto_20190609_1000'),
    ]

    operations = [
    ]
