# Generated by Django 2.2.1 on 2019-06-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20190609_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='ma',
            field=models.ManyToManyField(blank=True, default=None, to='api.Magazine'),
        ),
    ]
