# Generated by Django 2.2.2 on 2019-06-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20190609_1617'),
        ('api', '0038_merge_20190609_1014'),
    ]

    operations = [
    ]
