# Generated by Django 2.2.1 on 2019-06-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_merge_20190609_2030'),
        ('api', '0040_merge_20190609_1413'),
    ]

    operations = [
    ]
