# Generated by Django 2.2.2 on 2019-06-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190610_0356'),
        ('api', '0042_auto_20190609_2158'),
    ]

    operations = [
    ]
